In [1]:
import pandas as pd

In [2]:
#headerList = ['id','tweet'] #header=headerList
train = pd.read_csv("sentimental.csv",encoding='latin-1')
#train.columns=["a", "b"]

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   No.     28 non-null     int64
 1   tweet   28 non-null     object
dtypes: int64(1), object(1)
memory usage: 576.0+ bytes

In [4]:
train.head()

   No.                                              tweet
0    1  #milkquota goes and the fucking tree huggers a...
1    2  Really sceptical about the end of Milk Quotas....
2    3  #EU #MilkQuota being lifted will do 1 thing, i...
3    4  Dairy farmers' fears about the end of the #mil...
4    5  Happy #MilkQuota Day, everyone. Big day for th...

In [5]:
train["word_count"] = train["tweet"].apply(lambda x:len(str(x).split(" ")))
train["char_count"]=train["tweet"].str.len()
train.head()

,No.,tweet,word_count,char_count
0,1,#milkquota goes and the fucking tree huggers a...,23,140
1,2,Really sceptical about the end of Milk Quotas....,18,115
2,3,"#EU #MilkQuota being lifted will do 1 thing, i...",22,140
3,4,Dairy farmers' fears about the end of the #mil...,14,109
4,5,"Happy #MilkQuota Day, everyone. Big day for th...",13,88

In [6]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\fenix\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [7]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [8]:
train["stopwords"] =train ["tweet"].apply(lambda x: len([x for x in x.split()if x in stop]))
train["hashtag"] =train ["tweet"].apply(lambda x: len([x for x in x.split()if x.startswith("#")]))
train["upper"] =train ["tweet"].apply(lambda x: len([x for x in x.split()if x.isupper()]))
train.head()

,No.,tweet,word_count,char_count,stopwords,hashtag,upper
0,1,#milkquota goes and the fucking tree huggers a...,23,140,12,1,0
1,2,Really sceptical about the end of Milk Quotas....,18,115,6,2,1
2,3,"#EU #MilkQuota being lifted will do 1 thing, i...",22,140,6,2,1
3,4,Dairy farmers' fears about the end of the #mil...,14,109,5,1,0
4,5,"Happy #MilkQuota Day, everyone. Big day for th...",13,88,3,2,0

In [9]:
train["tweet_clean"]=train["tweet"].str.replace("[^\w\s]","")

C:\Users\fenix\AppData\Local\Temp/ipykernel_8552/3788428314.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  train["tweet_clean"]=train["tweet"].str.replace("[^\w\s]","")

In [10]:
train.head()

,No.,tweet,word_count,char_count,stopwords,hashtag,upper,tweet_clean
0,1,#milkquota goes and the fucking tree huggers a...,23,140,12,1,0,milkquota goes and the fucking tree huggers ar...
1,2,Really sceptical about the end of Milk Quotas....,18,115,6,2,1,Really sceptical about the end of Milk Quotas ...
2,3,"#EU #MilkQuota being lifted will do 1 thing, i...",22,140,6,2,1,EU MilkQuota being lifted will do 1 thing itll...
3,4,Dairy farmers' fears about the end of the #mil...,14,109,5,1,0,Dairy farmers fears about the end of the milkq...
4,5,"Happy #MilkQuota Day, everyone. Big day for th...",13,88,3,2,0,Happy MilkQuota Day everyone Big day for the I...

In [11]:
train['tweet_clean'] = train['tweet_clean'].apply(lambda x: " ".join(x.lower() for x in x.split()))
train['tweet_clean'] = train['tweet_clean'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

In [12]:
from textblob import TextBlob
train["tweet_clean"]  [:5].apply(lambda x: str(TextBlob(x).correct()))

0    milkquota goes fucking tree hunger tapping env...
1    really sceptic end milk quotas even seeing tod...
2    e milkquota lifted 1 thing till force small pr...
3    dairy farmers fears end milkquota exaggerated ...
4    happy milkquota day everyone big day irish int...
Name: tweet_clean, dtype: object

In [13]:
train["tweet_clean"] [:].apply(lambda x: str(TextBlob(x).sentiment))

0            Sentiment(polarity=-0.6, subjectivity=0.8)
1             Sentiment(polarity=0.2, subjectivity=0.2)
2           Sentiment(polarity=-0.25, subjectivity=0.4)
3            Sentiment(polarity=-0.5, subjectivity=1.0)
4           Sentiment(polarity=0.2, subjectivity=0.275)
5             Sentiment(polarity=0.8, subjectivity=1.0)
6             Sentiment(polarity=0.0, subjectivity=1.0)
7             Sentiment(polarity=0.0, subjectivity=0.0)
8            Sentiment(polarity=0.25, subjectivity=0.5)
9             Sentiment(polarity=0.0, subjectivity=1.0)
10    Sentiment(polarity=0.06818181818181818, subjec...
11    Sentiment(polarity=-0.004761904761904763, subj...
12          Sentiment(polarity=-0.25, subjectivity=0.4)
13            Sentiment(polarity=0.0, subjectivity=0.0)
14    Sentiment(polarity=-0.32500000000000007, subje...
15           Sentiment(polarity=-0.5, subjectivity=0.9)
16          Sentiment(polarity=0.35, subjectivity=0.55)
17          Sentiment(polarity=0.4, subjectivity=0.375)
18    Sentiment(polarity=0.3666666666666667, subject...
19        Sentiment(polarity=-0.1875, subjectivity=0.5)
20            Sentiment(polarity=0.0, subjectivity=0.0)
21    Sentiment(polarity=0.3, subjectivity=0.6333333...
22          Sentiment(polarity=0.75, subjectivity=0.95)
23    Sentiment(polarity=0.21212121212121213, subjec...
24    Sentiment(polarity=-0.004761904761904763, subj...
25            Sentiment(polarity=0.0, subjectivity=0.0)
26            Sentiment(polarity=0.0, subjectivity=0.3)
27    Sentiment(polarity=0.23035714285714284, subjec...
Name: tweet_clean, dtype: object

In [14]:
train['sentiment'] = train['tweet_clean'].apply(lambda x: TextBlob(x).sentiment[0] )
train.head(28)

,No.,tweet,word_count,char_count,stopwords,hashtag,upper,tweet_clean,sentiment
0,1,#milkquota goes and the fucking tree huggers a...,23,140,12,1,0,milkquota goes fucking tree huggers yapping en...,-0.600000
1,2,Really sceptical about the end of Milk Quotas....,18,115,6,2,1,really sceptical end milk quotas even seeing t...,0.200000
2,3,"#EU #MilkQuota being lifted will do 1 thing, i...",22,140,6,2,1,eu milkquota lifted 1 thing itll force small p...,-0.250000
3,4,Dairy farmers' fears about the end of the #mil...,14,109,5,1,0,dairy farmers fears end milkquota exaggerated ...,-0.500000
4,5,"Happy #MilkQuota Day, everyone. Big day for th...",13,88,3,2,0,happy milkquota day everyone big day irish int...,0.200000
5,6,Happy No #milkquota day to all #TeamDairy ;),8,44,2,2,0,happy milkquota day teamdairy,0.800000
6,7,It's over! In tmw's \n@Independent.ie I'm talk...,18,139,3,3,0,tmws independentie im talking end milkquota lu...,0.000000
7,8,There goes the #MilkQuota and no its not an #A...,21,118,9,2,0,goes milkquota aprilfools money mountain versu...,0.000000
8,9,So are the flood gates all open from tomorrow?...,25,134,10,1,0,flood gates open tomorrow anybody guess many l...,0.250000
9,10,Two hours and counting. In tmw's \n@Independen...,20,142,5,2,0,two hours counting tmws independent_ie im talk...,0.000000
10,11,It's over #milkquota New era for EU #dairy. Br...,13,68,4,2,1,milkquota new era eu dairy bring white gold,0.068182
11,12,I'm glad the #MilkQuota is gone. I'm sick of p...,19,102,6,1,1,im glad milkquota gone im sick powermad eurocr...,-0.004762
12,13,TheGreenParty: RT MollyMEP: Ending EU #milkquo...,19,116,5,2,2,thegreenparty rt mollymep ending eu milkquota ...,-0.250000
13,14,simoncoveney\n Sustainable intensification? Ar...,19,140,8,1,0,simoncoveney sustainable intensification jokin...,0.000000
14,15,Did they falsely promised benefits to small fa...,19,115,9,1,0,falsely promised benefits small farmers abolit...,-0.325000
15,16,Milk price dropped making farmers furious afte...,19,125,5,1,1,milk price dropped making farmers furious remo...,-0.500000
16,17,"Driving through Ireland this weekend, never no...",13,87,4,1,0,driving ireland weekend never noticed fields f...,0.350000
17,18,A great day for Irish farmers #milkquotas #iri...,9,85,1,2,1,great day irish farmers milkquotas irishfarmin...,0.400000
18,19,No quick fixes available after #MilkQuotas end...,15,110,3,1,1,quick fixes available milkquotas ending prices...,0.366667
19,20,little brother lives for ear to the ground #gl...,11,78,3,3,0,little brother lives ear ground gluedtothetele...,-0.187500
20,21,to bring rising milk production under control ...,15,109,4,2,0,bring rising milk production control prevent b...,0.000000
21,22,"To all Farmers who bought the Coveney line ""qu...",22,139,6,1,0,farmers bought coveney line quotasbad free mar...,0.300000
22,23,Our bottle fed calf has been successfully reun...,15,92,5,1,0,bottle fed calf successfully reunited mothers ...,0.750000
23,24,#milkquota Are we to expect countless new exot...,22,132,7,1,0,milkquota expect countless new exotic yogurts ...,0.212121
24,25,I'm glad the #MilkQuota is gone. I'm sick of p...,19,102,6,1,1,im glad milkquota gone im sick powermad eurocr...,-0.004762
25,26,Ireland's biggest dairy farmer warns against q...,9,81,1,0,0,irelands biggest dairy farmer warns quota euph...,0.000000
26,27,We have been told the end of milk quotas will ...,25,124,12,0,0,told end milk quotas create thousands irish jo...,0.000000
27,28,The end of milk quotas presents an opportunity...,47,251,19,0,2,end milk quotas presents opportunity young amb...,0.230357

In [15]:
X = train['tweet']